//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printing_and_Engraving_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int CheckOutID { get; set; }
        public int UserID { get; set; }
        public int OrderID { get; set; }
        public decimal TotalPrice { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string CardHolderZip { get; set; }
        public string CardHolderState { get; set; }
        public string CardHolderCity { get; set; }
        public string CardHolderAddress2 { get; set; }
        public string CardHolderAddress1 { get; set; }
        public string CardNumber { get; set; }
        public string CardHolderName { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
