//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Printing_and_Engraving_Site
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int EmployeeID { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
        public Nullable<int> UserRoleID { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
